<a href="https://colab.research.google.com/github/Pranavlovescode/Bangluru-Price-predictor/blob/master/bangluru_price_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt
import numpy as np

In [24]:
df = pd.read_csv('bengaluru_house_prices.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [25]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [26]:
df2 = df.drop(['area_type','availability','society','balcony'],axis=1)
df2.head(10)

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00
5                Whitefield      2 BHK       1170   2.0   38.00
6          Old Airport Road      4 BHK       2732   4.0  204.00
7              Rajaji Nagar      4 BHK       3300   4.0  600.00
8              Marathahalli      3 BHK       1310   3.0   63.25
9              Gandhi Bazar  6 Bedroom       1020   6.0  370.00

In [33]:
df2['size'].dtype

dtype('O')

In [37]:
df2['bhk'] = df2['size'].apply(lambda x : x.split(' ')[0])
df3 = df2.drop(['size'],axis=1)
df3.head()

                   location total_sqft  bath   price bhk
0  Electronic City Phase II       1056   2.0   39.07   2
1          Chikka Tirupathi       2600   5.0  120.00   4
2               Uttarahalli       1440   2.0   62.00   3
3        Lingadheeranahalli       1521   3.0   95.00   3
4                  Kothanur       1200   2.0   51.00   2

In [44]:
df3.isnull().sum()
df3.head(50)

                    location   total_sqft  bath   price bhk
0   Electronic City Phase II         1056   2.0   39.07   2
1           Chikka Tirupathi         2600   5.0  120.00   4
2                Uttarahalli         1440   2.0   62.00   3
3         Lingadheeranahalli         1521   3.0   95.00   3
4                   Kothanur         1200   2.0   51.00   2
5                 Whitefield         1170   2.0   38.00   2
6           Old Airport Road         2732   4.0  204.00   4
7               Rajaji Nagar         3300   4.0  600.00   4
8               Marathahalli         1310   3.0   63.25   3
9               Gandhi Bazar         1020   6.0  370.00   6
10                Whitefield         1800   2.0   70.00   3
11                Whitefield         2785   5.0  295.00   4
12        7th Phase JP Nagar         1000   2.0   38.00   2
13                 Gottigere         1100   2.0   40.00   2
14                  Sarjapur         2250   3.0  148.00   3
15               Mysore Road         1175   2.0   73.50   2
16             Bisuvanahalli         1180   3.0   48.00   3
17     Raja Rajeshwari Nagar         1540   3.0   60.00   3
18     Ramakrishnappa Layout         2770   4.0  290.00   3
19        Manayata Tech Park         1100   2.0   48.00   2
20                   Kengeri          600   1.0   15.00   1
21                Binny Pete         1755   3.0  122.00   3
22               Thanisandra         2800   5.0  380.00   4
23                 Bellandur         1767   3.0  103.00   3
24               Thanisandra          510   1.0   25.25   1
25           Mangammanapalya         1250   3.0   56.00   3
26           Electronic City          660   1.0   23.10   2
27                Whitefield         1610   3.0   81.00   3
28          Ramagondanahalli         1151   2.0   48.77   2
29           Electronic City         1025   2.0   47.00   3
30                 Yelahanka  2100 - 2850   4.0  186.00   4
31             Bisuvanahalli         1075   2.0   35.00   3
32                    Hebbal         1760   2.0  123.00   3
33     Raja Rajeshwari Nagar         1693   3.0   57.39   3
34             Kasturi Nagar         1925   3.0  125.00   3
35            Kanakpura Road          700   2.0   36.00   2
36  Electronics City Phase 1         1070   2.0   45.50   2
37              Kundalahalli         1724   3.0  125.00   3
38            Chikkalasandra         1290   2.0   56.12   3
39               Uttarahalli         1143   2.0   45.00   2
40             Murugeshpalya         1296   2.0   81.00   2
41            Sarjapur  Road         1254   3.0   38.00   3
42               Ganga Nagar          600   1.0   38.00   1
43                 Yelahanka          660   1.0   48.00   1
44            Kanakpura Road      1330.74   2.0   91.79   2
45                HSR Layout          600   9.0  200.00   8
46              Doddathoguru          970   2.0   33.00   2
47                Whitefield         1459   2.0   94.82   2
48                  KR Puram          800   1.0  130.00   2
49          Himagiri Meadows          869   2.0   36.00   2

In [45]:
df3['location'].value_counts()

location
Whitefield                        540
Sarjapur  Road                    400
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: count, Length: 1305, dtype: int64